FROM node:22.6.0-bullseye-slim

LABEL version="1.0"
LABEL description="Imagem Node 22.6 costumizada."
LABEL manintainer="Marcos Pachêco"
LABEL email="marcos.hr.pacheco@gmail.com"

RUN apt-get update 
RUN apt-get install -y bash